# Generated by Django 4.0.3 on 2022-03-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_dog_dogtoys_dog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogtoy',
            name='img',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
